jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.BYTELEGENDBOT_TOKEN }}
    - continue-on-error: true
      name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - continue-on-error: true
      id: yarn-cache-dir-path
      name: Get yarn cache directory path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock')
          }}
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        restore-keys: '${{ runner.os }}-yarn-${{ matrix.node-version }}

          '
    - continue-on-error: true
      run: yarn config set script-shell /bin/bash && yarn
      working-directory: github1s
    - continue-on-error: true
      run: yarn build:vscode
      working-directory: github1s
    - continue-on-error: true
      run: yarn yalc
      working-directory: github1s
    - continue-on-error: true
      run: yarn build && yarn hash
      working-directory: github1s
    - continue-on-error: true
      run: find github1s/dist -name '*.js.map' -exec cp .github/empty.json {} \;
    - continue-on-error: true
      run: find github1s/dist -name '*.gif' | xargs rm -rf
    - continue-on-error: true
      run: find github1s/dist -name 'learn.svg' | xargs rm -rf
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: webeditor
        path: github1s/dist
  test:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.BYTELEGENDBOT_TOKEN }}
    - continue-on-error: true
      uses: actions/download-artifact@v3
      with:
        name: webeditor
        path: github1s/dist
    - continue-on-error: true
      name: Display structure of downloaded files
      run: ls -alth github1s/dist
    - continue-on-error: true
      name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - continue-on-error: true
      run: yarn config set script-shell /bin/bash && yarn install
      working-directory: github1s
    - continue-on-error: true
      run: yarn serve > ./output 2>&1 &
      working-directory: github1s
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: 'server:app:webEditorBrowserTest -DagreePublicBuildScanTermOfService=yes
          -Dforest.github.read.token=${{ secrets.BYTELEGENDBOT_TOKEN }} -Dforest.test.enableRecording=true

          '
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: 'server/app/build/tmp/**/*.mp4

          server/app/build/reports/test

          '
name: build-test-webeditor
on:
  repository_dispatch:
    types: trigger-ga___build-test-webeditor.yml
