jobs:
  browser-test:
    if: ${{ github.event.pull_request.author_association != 'CONTRIBUTOR' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.BYTELEGENDBOT_TOKEN }}
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: server:app:browserTest -DagreePublicBuildScanTermOfService=yes
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: 'server/app/build/tmp/**/*.mp4

          server/app/build/reports/tests

          '
  contributor-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: false
    - continue-on-error: true
      name: Checkout server-opensource
      run: git submodule update --init -- game-data
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Ktlint
      uses: gradle/gradle-build-action@v2
      with:
        arguments: ktlint -DagreePublicBuildScanTermOfService=yes
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: server-opensource:check utils:checkLicenses -DagreePublicBuildScanTermOfService=yes
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: 'server/app/build/tmp/**/*.mp4

          server/app/build/reports/tests

          '
  integ-test:
    if: ${{ github.event.pull_request.author_association != 'CONTRIBUTOR' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.BYTELEGENDBOT_TOKEN }}
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: ktlint server:app:integTest -DagreePublicBuildScanTermOfService=yes
          -Dforest.github.read.token=${{ secrets.GITHUB_TOKEN }}
  member-check:
    if: ${{ github.event.pull_request.author_association != 'CONTRIBUTOR' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.BYTELEGENDBOT_TOKEN }}
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Ktlint
      uses: gradle/gradle-build-action@v2
      with:
        arguments: ktlint -DagreePublicBuildScanTermOfService=yes
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check -x server:app:browserTest -x server:app:integTest -x server:app:webEditorBrowserTest
          -DagreePublicBuildScanTermOfService=yes
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: 'server/app/build/reports/tests

          '
name: check
on:
  repository_dispatch:
    types: trigger-ga___check.yml
