jobs:
  deploy:
    if: github.repository == 'ByteLegend/ByteLegend'
    name: Deploy webeditor
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: determine-webeditor-commit
      name: Determine webeditor commit to deploy
      uses: actions/github-script@v5
      with:
        script: "if ('${{ github.event.inputs.deployCommit }}' == 'latest') {\n  const\
          \ response = await github.rest.git.getRef({\n    owner: 'ByteLegend',\n\
          \    repo: 'ByteLegend',\n    ref: 'heads/${{ github.event.inputs.fromBranch\
          \ }}'\n  })\n  console.log(`Commit to deploy: ${response.data.object.sha}`)\n\
          \  core.setOutput('deploy-commit', response.data.object.sha)\n} else {\n\
          \  console.log(`Commit to deploy: ${{ github.event.inputs.deployCommit }}`)\n\
          \  core.setOutput('deploy-commit', '${{ github.event.inputs.deployCommit\
          \ }}')\n}\n"
    - continue-on-error: true
      uses: dawidd6/action-download-artifact@v2
      with:
        commit: ${{ steps.determine-webeditor-commit.outputs.deploy-commit }}
        name: webeditor
        path: github1s/dist
        workflow: build-test-webeditor.yml
        workflow_conclusion: completed
    - continue-on-error: true
      run: tree github1s/dist
    - continue-on-error: true
      name: Upload /static to s3 Seoul
      run: 'docker run -v $GITHUB_WORKSPACE/github1s/dist:/dist -e AWS_ACCESS_KEY_ID=${{secrets.ACCESS_KEY_ID_SEOUL}}
        -e AWS_SECRET_ACCESS_KEY=${{secrets.SECRET_ACCESS_KEY_SEOUL}} -e AWS_DEFAULT_REGION=ap-northeast-2
        amazon/aws-cli s3 sync /dist/static s3://bytelegend-web-editor/static

        '
    - continue-on-error: true
      name: Upload /static to s3 Beijing
      run: 'docker run -v $GITHUB_WORKSPACE/github1s/dist:/dist -e AWS_ACCESS_KEY_ID=${{secrets.ACCESS_KEY_ID_BEIJING}}
        -e AWS_SECRET_ACCESS_KEY=${{secrets.SECRET_ACCESS_KEY_BEIJING}} -e AWS_DEFAULT_REGION=cn-north-1
        amazon/aws-cli s3 sync /dist/static s3://bytelegend-web-editor/static

        '
    - continue-on-error: true
      name: Sync index.html to s3 Seoul
      run: 'docker run -v $GITHUB_WORKSPACE/github1s/dist:/dist -e AWS_ACCESS_KEY_ID=${{secrets.ACCESS_KEY_ID_SEOUL}}
        -e AWS_SECRET_ACCESS_KEY=${{secrets.SECRET_ACCESS_KEY_SEOUL}} -e AWS_DEFAULT_REGION=ap-northeast-2
        amazon/aws-cli s3 sync --exclude ''static/*'' --delete /dist s3://bytelegend-web-editor

        '
    - continue-on-error: true
      name: Sync /index.html to s3 Beijing
      run: 'docker run -v $GITHUB_WORKSPACE/github1s/dist:/dist -e AWS_ACCESS_KEY_ID=${{secrets.ACCESS_KEY_ID_BEIJING}}
        -e AWS_SECRET_ACCESS_KEY=${{secrets.SECRET_ACCESS_KEY_BEIJING}} -e AWS_DEFAULT_REGION=cn-north-1
        amazon/aws-cli s3 sync --exclude ''static/*'' --delete /dist s3://bytelegend-web-editor

        '
name: deploy-webeditor
on:
  repository_dispatch:
    types: trigger-ga___deploy-webeditor.yml
