jobs:
  markdown-lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: false
    - continue-on-error: true
      name: Fetch game-data
      run: git submodule update --init -- game-data
    - continue-on-error: true
      name: markdownlint
      uses: nosborn/github-action-markdown-cli@v3.0.1
      with:
        config_file: .markdownlint.yaml
        files: .
name: Markdown Lint
on:
  repository_dispatch:
    types: trigger-ga___markdownlint.yml
