jobs:
  release:
    if: github.repository == 'ByteLegend/ByteLegend'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.BYTELEGENDBOT_TOKEN }}
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      env:
        ACCESS_KEY_ID_BEIJING: ${{ secrets.ACCESS_KEY_ID_BEIJING }}
        ACCESS_KEY_ID_SEOUL: ${{ secrets.ACCESS_KEY_ID_SEOUL }}
        GITHUB_TOKEN: ${{ secrets.BYTELEGENDBOT_TOKEN }}
        SECRET_ACCESS_KEY_BEIJING: ${{ secrets.SECRET_ACCESS_KEY_BEIJING }}
        SECRET_ACCESS_KEY_SEOUL: ${{ secrets.SECRET_ACCESS_KEY_SEOUL }}
      name: Release to ECR and S3
      uses: gradle/gradle-build-action@v2
      with:
        arguments: release -PupdateVersions -DagreePublicBuildScanTermOfService=yes
name: release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
