jobs:
  check-and-release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.BYTELEGENDBOT_TOKEN }}
    - continue-on-error: true
      name: Check and Release
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :server:github-release:uploadRepoCleanerToGitHubRelease -DgitHubToken=${{
          secrets.BYTELEGENDBOT_TOKEN }} -DagreePublicBuildScanTermOfService=yes
name: Release repo-cleaner
on:
  repository_dispatch:
    types: trigger-ga___release-repo-cleaner.yml
